"""create_answer_table

Revision ID: 4dffe048bf59
Revises:
Create Date: 2024-11-23 13:32:30.363465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2561e276a120'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '16c052e011bc'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        'answer',
        sa.Column('answer_id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.user_id'), nullable=False),
        sa.Column('text_id', sa.Integer, sa.ForeignKey('text.text_id'), nullable=False),
        sa.Column('difficult', sa.Integer, nullable=False),
        sa.Column('interest', sa.Integer, nullable=False),
        sa.Column('created_at', sa.TIMESTAMP, server_default=sa.func.current_timestamp())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
